[versions]
junit = "4.13.2"
mockito = "3.12.4"
androidx_core = "1.7.0"

[libraries]
junit = { module = "junit:junit", version.ref = "junit" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
androidx_core = { module = "androidx.core:core-ktx", version.ref = "androidx_core" }

[bundles]
testLibs = ["junit", "mockito"]